### ISSUE TITLE
not clear, what to do with this

### ISSUE THREAD

**Issue by dulhaver** [frappe/chart_of_accounts_builder#1]
from the README it doesn't get clear how this could be used

what I could need is a tool that builds a coa.py based on a csv file

maybe this is an App that you can install and then it can build a coa.py from the Chart of Accounts someone has manually made inside the ERPNext Accounts?

**Comment by anandpdoshi** [comment]
No this is supposed to be a web application like translate.erpnext.com to enable chart of accounts contribution

**Comment by dulhaver** [comment]
so, how or where can one use it? Does it simplify the coding process in any way? I mean in terms of you provide data like name of accounts, groups, etc ... and the code is being build for you?

**Comment by nabinhait** [comment]
No, it will be used in a portal for contributing chart of accounts by community for their own countries.

**Comment by dulhaver** [comment]
"will be used…" sounds like it can't be used yet. Is that so?

**Comment by nabinhait** [comment]
Yeah, the project is not completed yet.
