### ISSUE TITLE
How to use after contribute?

### ISSUE THREAD

**Issue by robert1112** [frappe/chart_of_accounts_builder#23]
Hi I am working here. https://charts.erpnext.com/all_charts
But wondering how to use it after submit my own chart for my country? Thanks

**Comment by nabinhait** [comment]
On submission of a chart of accounts, we get an automated email regarding this. Then we test it and if everything is ok, include it in the erpnext repo.
It is also a good idea to create a github issue, after submitting a chart, with the name and country of the chart of accounts.

**Comment by robert1112** [comment]
Hi @nabinhait  Thanks for your reply. After creating, how can I used it immediately? The reason is I am thinking of creating on my installation directly or contribute first? Thanks.

**Comment by nabinhait** [comment]
Currently there is no way to download it by yourself, after submission of the charts. I think it will be useful if we add a button to download the chart. And the button will be visible only after successful submission of the charts, to ensure the contribution.

Added a github issue https://github.com/frappe/chart_of_accounts_builder/issues/24

**Comment by robert1112** [comment]
Thank you @nabinhait
