### ISSUE TITLE
Fork is not working properly!

### ISSUE THREAD

**Issue by robert1112** [frappe/chart_of_accounts_builder#26]
Hi I tried couple times to favor and fork some submitted charts but I got only a BLANK chart with the same chat title with different sequential number. 

![](https://ws2.sinaimg.cn/large/006tNc79gy1fib5tv6zk4j31kw0epta4.jpg)

**Comment by nabinhait** [comment]
Could not replicate, I can successfully fork any existing chart. Which browser are you using?

**Comment by robert1112** [comment]
Safari 10.1.1

**Comment by nabinhait** [comment]
Yes, some charts cannot be forked (e.g. France). Because it has some errors. In this case, you have to create from scratch or fork any user contributed charts for that country.

I will rename "Standard Charts"  to "Unverified Charts".

**Comment by nabinhait** [comment]
@robert1112 By the way, I am thinking to merge below chart in erpnext repository as a standard chart for France. Can you please verify it or add a comment on https://github.com/frappe/erpnext/issues/7916.

https://charts.erpnext.com/chart?company=France%20-%20Plan%20Comptable%20G%C3%A9n%C3%A9ral-6&forked=1&submitted=1

**Comment by robert1112** [comment]
Hi I am afraid I cannot verify anything. I know zero about France accounting.
