### ISSUE TITLE
Account Types?

### ISSUE THREAD

**Issue by robert1112** [frappe/chart_of_accounts_builder#27]
Hi I am ready to upload a chart for Taiwan. The chart is based on IFRSs for general use. But I cannot find the account type below:
**Stock Received But Not Billed
Expenses Included In Valuation
Temporary Opening**
Are these necessary? Are they created for ERP only, not for accounting? Thanks.

**Comment by nabinhait** [comment]
Yes, those accounts are necessary for perpetual inventory. I will suggest to add an account with the same name as the above account type.

**Comment by robert1112** [comment]
Which category, Liability, Asset or..., should these account type should go?
**_Stock Received But Not Billed
Expenses Included In Valuation
Temporary Opening
Stock Adjustment_**
And what happen if it goes to the wrong category? What about subcategory? Does it matter?
Thanks.

**Comment by nabinhait** [comment]
Stock Received But Not Billed - `Liability`
Expenses Included In Valuation - `Expense` - under COGS group
Temporary Opening - `Asset`
Stock Adjustment - `Expense` - under COGS group

**Comment by robert1112** [comment]
Thank you so much! It is not quite like IFRSs tree but I will take a look. Thank you.
