### ISSUE TITLE
New chart of account didn't  work

### ISSUE THREAD

**Issue by robert1112** [frappe/chart_of_accounts_builder#28]
Hi 

I created and download CoA and successfully upload to the directory. I can select the new one from Company page. But it didnt take effect on CoA page even tried "bench --site all clear-website-cache" and refresh the page couple times. 

What else should I try? Thanks.

**Comment by robert1112** [comment]
I waited a day but still dont see any update on CoA! Any help or advice, please? Thanks.

**Comment by nabinhait** [comment]
Are you trying to create a new company? Chart of accounts is created only on creation of a new company or if there is no chart of accounts for the company.

**Comment by robert1112** [comment]
Hi I tried to choose the new chart I uploaded to replace the existing one. But nothing happened.

**Comment by nabinhait** [comment]
Which chart are you trying?

**Comment by robert1112** [comment]
It is Taiwan - Chart of Accounts-4.
It works if I created a new company and choose it as default CoA.

**Comment by nabinhait** [comment]
Yes, that is how it works. It does not replace existing COA for existing company.

**Comment by nabinhait** [comment]
Thanks for contributing the chart. 

Sent a PR (https://github.com/frappe/erpnext/pull/10435)

**Comment by robert1112** [comment]
@nabinhait  
Here is the update. Problem solved. I deleted the old company transaction first and then I can select the new chart and it works. Maybe you can update this info to the help page, after you verify this. People normally have default CoA already, so they generally prefer to change the chart instead of creating a new company with the new chart. Thanks for the community and your support!

**Comment by robert1112** [comment]
@nabinhait 
2nd thought. The reason why I worked this time is because I login as Admin which create the company in the first place. 😃
