### ISSUE TITLE
Improve portal

### ISSUE THREAD

**Issue by nabinhait** [frappe/chart_of_accounts_builder#35]
- [x] Implement account numbers
- [x] A submitted chart should be editable by the creator without need of forking. Send a notification to developers@erpnext.com on submission of editable version.
- [x] Add provision to name a chart, add custom field in company.
- [x] Ask Domain on submission(if any)
- [x] Add a custom field in Company to track if the chart is included in erpnext repository.
- [x] Make necessary changes to support all account types
- [x] Populate predefined country list for filtering
- [x] Delete option for un-submitted charts
- [x] Email comments
- [x] Fix visibility of number of stars inside chart page
- [x] Tabular view of "My charts", "User Contributed Charts", "Unverified charts" and "Available on ERPNext"
- [x] Update help page

**Comment by parsimonyERP** [comment]
When trying to delete a CoA that I have created, I get a button that asks for confirmation of deletion and when I click "OK", I get Permission denied. 

https://charts.erpnext.com/chart?company=United%20States%20-%20Chart%20of%20Accounts-8-1&forked=1&submitted=0&owner=michael@parsimony.com

**Comment by parsimonyERP** [comment]
Download the CoA.  The download button does not seem to work.

**Comment by parsimonyERP** [comment]
Renaming CoA doesn't work.  When I done editing the CoA, I choose "Submit".  That gives me a dropdown window with an option to name the Chart.  Change it to "United States - eCommerce" and click on Submit.  But when CoA's are listed in the master list of my CoA's, the old name is still in place even after a page refresh.
